// Auth
export const REGISTER_INITIAL_STEP_SUCCEEEDED =
  "REGISTER_INITIAL_STEP_SUCCEEEDED";
export const REGISTER_FINAL_STEP_SUCCEEEDED = "REGISTER_FINAL_STEP_SUCCEEEDED";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGOUT_SUCCEEDED = "LOGOUT_SUCCEEDED";

// Messages
export const GET_MESSAGES = "GET_MESSAGES";
export const MESSAGES_LOADING = "MESSAGES_LOADING";
export const MESSAGES_LOADED_ON_CHATROOM_JOIN =
  "MESSAGES_LOADED_ON_CHATROOM_JOIN";
export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";

// Chatrooms
export const GET_CHATROOMS = "GET_CHATROOMS";
export const ADD_CHATROOM_SUCCEEDED = "ADD_CHATROOM_SUCCEEDED";
export const SOCKET_ADDED_CHATROOM = "SOCKET_ADDED_CHATROOM";
export const ADD_CHATROOM_DIALOG_OPENED = "ADD_CHATROOM_DIALOG_OPENED";
export const ADD_CHATROOM_DIALOG_CLOSED = "ADD_CHATROOM_DIALOG_CLOSED";
export const RECEIVED_CURRENT_CHATROOM_USERS =
  "RECEIVED_CURRENT_CHATROOM_USERS";
export const DELETE_CHATROOM = "DELETE_CHATROOM";
export const USER_JOINED_CHATROOM = "USER_JOINED_CHATROOM";
export const ACCOUNT_UPDATED = "ACCOUNT_UPDATED";

export const USER_TYPING = "USER_TYPING";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION ";
