// Auth
export const REGISTER_SUCCEEEDED = "REGISTER_SUCCEEEDED";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_ERROR_CLEARED = "LOGIN_ERROR_CLEARED";
export const LOGOUT_SUCCEEDED = "LOGOUT_SUCCEEDED";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const USER_LOADED = "USER_LOADED";

// Messages
export const GET_MESSAGES = "GET_MESSAGES";
export const MESSAGES_LOADED_ON_CHATROOM_JOIN =
  "MESSAGES_LOADED_ON_CHATROOM_JOIN";
export const CHAT_MESSAGE_SENT = "  CHAT_MESSAGE_SENT";
export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
export const PRIVATE_MESSAGE_SENT = "PRIVATE_MESSAGE_SENT";

// Chatrooms
export const GET_CHATROOMS = "GET_CHATROOMS";
export const REQUEST_NEW_CHATROOM = "REQUEST_NEW_CHATROOM";
export const ADD_CHATROOM_SUCCEEDED = "ADD_CHATROOM_SUCCEEDED";
export const ADD_CHATROOM_FAILED = "ADD_CHATROOM_FAILED";
export const SOCKET_ADDED_CHATROOM = "SOCKET_ADDED_CHATROOM";
export const ADD_CHATROOM_ERROR_CLEARED = "ADD_CHATROOM_ERROR_CLEARED";
export const ADD_CHATROOM_SUCCESS_EXPIRED = "ADD_CHATROOM_SUCCESS_EXPIRED";
export const ADD_CHATROOM_DIALOG_OPENED = "ADD_CHATROOM_DIALOG_OPENED";
export const ADD_CHATROOM_DIALOG_CLOSED = "ADD_CHATROOM_DIALOG_CLOSED";
export const JOIN_CHATROOM_SUCCEEDED = "JOIN_CHATROOM_SUCCEEDED";
export const RECEIVED_CURRENT_CHATROOM_USERS =
  "RECEIVED_CURRENT_CHATROOM_USERS";
export const USER_JOINED_CHATROOM = "USER_JOINED_CHATROOM";
export const USER_LEFT_CHATROOM = "USER_LEFT_CHATROOM";
export const ACCOUNT_UPDATED = "ACCOUNT_UPDATED";
export const USER_TYPING = "USER_TYPING";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION ";
